### ISSUE TITLE
Knife skin doesn't change when selected from menu

### ISSUE THREAD

**Issue by kus** [kgns/weapons#175] opened 2020-05-15 03:30 UTC
Hi,

I've followed the instructions carefully and installed your Weapons plugin on my Ubuntu server. You can see the commit here https://github.com/kus/csgo-modded-server/commit/852281c6b9abb3fccfc4b48950f350c6bf44cbf8

The menu loads when I type !knife but when I choose a knife my knife flickers and does an animation but the knife does not change.

When I change the map with your plugin loaded the server also crashes - which I'm talking to the author of PTaH about that here https://github.com/komashchenko/PTaH/issues/34

I have your gloves plugin installed also which works.

Any ideas why the knife skin doesn't change? I own a ★ StatTrak™ Karambit | Doppler to start with if that is causing an issue?

**Comment by kgns** [comment] 2020-07-30 10:47
This was caused by a SourceMod bug which has been fixed in June, so I'm closing this issue. Not a problem with this plugin

**Closed by kgns** 2020-07-30 10:47 UTC
