### ISSUE TITLE
Memory leaks and very terrible structuring for the plugin

### ISSUE THREAD

**Issue by shavitush** [kgns/weapons#70] opened 2018-12-28 13:06 UTC
This issue applies to both your `weapons` and `gloves` plugins. 

Dumping handles after running this plugin for half an hour has a whopping 1.2k handles open only from this plugin!

It looks like this:

```
0x8ce302b8	weapons.smx         	IBaseMenu           	345       
0x8ce402b9	weapons.smx         	IBaseMenu           	346       
0x8ce502ba	weapons.smx         	IBaseMenu           	348       
0x8ce602bb	weapons.smx         	IBaseMenu           	345       
0x8ce702bc	weapons.smx         	IBaseMenu           	182       
0x8ce902bd	weapons.smx         	IBaseMenu           	599       
0x8cea02be	weapons.smx         	IBaseMenu           	681       
0x8ceb02bf	weapons.smx         	IBaseMenu           	640       
0x8cec02c0	weapons.smx         	IBaseMenu           	582       
0x8ced02c1	weapons.smx         	IBaseMenu           	608       
0x8cee02c2	weapons.smx         	IBaseMenu           	561       
0x8cef02c3	weapons.smx         	IBaseMenu           	541       
0x8cf002c4	weapons.smx         	IBaseMenu           	644       
0x8cf102c5	weapons.smx         	IBaseMenu           	549       
0x8cf202c6	weapons.smx         	IBaseMenu           	740       
0x8cf302c7	weapons.smx         	IBaseMenu           	545       
0x8cf402c8	weapons.smx         	IBaseMenu           	606       
0x8cf502c9	weapons.smx         	IBaseMenu           	641       
0x8cf602ca	weapons.smx         	IBaseMenu           	284       
0x8cf702cb	weapons.smx         	IBaseMenu           	620       
0x8cf802cc	weapons.smx         	IBaseMenu           	542       
0x8cf902cd	weapons.smx         	IBaseMenu           	521       
0x8cfa02ce	weapons.smx         	IBaseMenu           	605       
0x8cfb02cf	weapons.smx         	IBaseMenu           	320       
0x8cfc02d0	weapons.smx         	IBaseMenu           	381       
0x8cfd02d1	weapons.smx         	IBaseMenu           	559       
0x8cfe02d2	weapons.smx         	IBaseMenu           	602       
0x8cff02d3	weapons.smx         	IBaseMenu           	559       
0x8d0002d4	weapons.smx         	IBaseMenu           	582       
0x8d0102d5	weapons.smx         	IBaseMenu           	599       
0x8d0202d6	weapons.smx         	IBaseMenu           	604       
0x8d0302d7	weapons.smx         	IBaseMenu           	481       
0x8d0402d8	weapons.smx         	IBaseMenu           	564       
0x8d0502d9	weapons.smx         	IBaseMenu           	442       
0x8d0602da	weapons.smx         	IBaseMenu           	559       
0x8d0702db	weapons.smx         	IBaseMenu           	522       
0x8d0802dc	weapons.smx         	IBaseMenu           	463       
0x8d0902dd	weapons.smx         	IBaseMenu           	521       
0x8d0a02de	weapons.smx         	IBaseMenu           	788       
0x8d0b02df	weapons.smx         	IBaseMenu           	790       
0x8d0c02e0	weapons.smx         	IBaseMenu           	787       
0x8d0d02e1	weapons.smx         	IBaseMenu           	591       
0x8d0e02e2	weapons.smx         	IBaseMenu           	595       
0x8d0f02e3	weapons.smx         	IBaseMenu           	790       
0x8d1002e4	weapons.smx         	IBaseMenu           	594       
0x8d1102e5	weapons.smx         	IBaseMenu           	594       
0x8d1202e6	weapons.smx         	IBaseMenu           	594       
0x8d1302e7	weapons.smx         	IBaseMenu           	789       
0x8d1402e8	weapons.smx         	IBaseMenu           	345       
0x8d1502e9	weapons.smx         	IBaseMenu           	346       
```

I will submit a pull request today for both plugins to fix this leak.

**Comment by kgns** [comment] 2019-01-10 00:12
after checking handle dumps and plugin logic I have found out that actually there is no memory leak. if you can check config.sp, you would see that the plugin creates menu handles for every weapon type in every language available.

so if you have all the languages available by default in addons/sourcemod/configs/languages.cfg, and have all the language config files from this addon, it will be 26 different languages for 48 different weapon types. which makes 26 * 48 = 1248 menu handles. I have chosen this logic to offer players the ability to see the skins in their own language, or in any other language as they please, while not have to modify the menu values on the fly every time someone opens one with different language set.

I have checked the amount of IBaseMenu handles on every server I have access to, and the number is a fixed intersection of the languages in language.cfg and weapons/configs/ folder multiplied by 48, which was intended back when I coded it (this was my first plugin for sourcemod btw)

in addition to the IBaseMenu handles, there are 1 x IDatabase and 3 x Trie handles (StringMap), which is again intended and none of those are leaking (i.e. not increasing in number as the server run time increases)

**Closed by kgns** 2019-01-10 00:12 UTC
